# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ifstatsbag_generic.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ifstatsbag_generic.proto',
  package='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters',
  syntax='proto3',
  serialized_pb=_b('\n\x18ifstatsbag_generic.proto\x12\\cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters\"1\n\x17ifstatsbag_generic_KEYS\x12\x16\n\x0einterface_name\x18\x01 \x01(\t\"\x9e\x08\n\x12ifstatsbag_generic\x12\x18\n\x10packets_received\x18\x32 \x01(\x04\x12\x16\n\x0e\x62ytes_received\x18\x33 \x01(\x04\x12\x14\n\x0cpackets_sent\x18\x34 \x01(\x04\x12\x12\n\nbytes_sent\x18\x35 \x01(\x04\x12\"\n\x1amulticast_packets_received\x18\x36 \x01(\x04\x12\"\n\x1a\x62roadcast_packets_received\x18\x37 \x01(\x04\x12\x1e\n\x16multicast_packets_sent\x18\x38 \x01(\x04\x12\x1e\n\x16\x62roadcast_packets_sent\x18\x39 \x01(\x04\x12\x14\n\x0coutput_drops\x18: \x01(\r\x12\x1a\n\x12output_queue_drops\x18; \x01(\r\x12\x13\n\x0binput_drops\x18< \x01(\r\x12\x19\n\x11input_queue_drops\x18= \x01(\r\x12\x1d\n\x15runt_packets_received\x18> \x01(\r\x12\x1e\n\x16giant_packets_received\x18? \x01(\r\x12\"\n\x1athrottled_packets_received\x18@ \x01(\r\x12\x1f\n\x17parity_packets_received\x18\x41 \x01(\r\x12)\n!unknown_protocol_packets_received\x18\x42 \x01(\r\x12\x14\n\x0cinput_errors\x18\x43 \x01(\r\x12\x12\n\ncrc_errors\x18\x44 \x01(\r\x12\x16\n\x0einput_overruns\x18\x45 \x01(\r\x12\x1f\n\x17\x66raming_errors_received\x18\x46 \x01(\r\x12\x1d\n\x15input_ignored_packets\x18G \x01(\r\x12\x14\n\x0cinput_aborts\x18H \x01(\r\x12\x15\n\routput_errors\x18I \x01(\r\x12\x18\n\x10output_underruns\x18J \x01(\r\x12\x1e\n\x16output_buffer_failures\x18K \x01(\r\x12\"\n\x1aoutput_buffers_swapped_out\x18L \x01(\r\x12\x10\n\x08\x61pplique\x18M \x01(\r\x12\x0e\n\x06resets\x18N \x01(\r\x12\x1b\n\x13\x63\x61rrier_transitions\x18O \x01(\r\x12\x19\n\x11\x61vailability_flag\x18P \x01(\r\x12\x16\n\x0elast_data_time\x18Q \x01(\r\x12)\n!seconds_since_last_clear_counters\x18R \x01(\r\x12\x1f\n\x17last_discontinuity_time\x18S \x01(\r\x12%\n\x1dseconds_since_packet_received\x18T \x01(\r\x12!\n\x19seconds_since_packet_sent\x18U \x01(\rb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_IFSTATSBAG_GENERIC_KEYS = _descriptor.Descriptor(
  name='ifstatsbag_generic_KEYS',
  full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic_KEYS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='interface_name', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic_KEYS.interface_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=171,
)


_IFSTATSBAG_GENERIC = _descriptor.Descriptor(
  name='ifstatsbag_generic',
  full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packets_received', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.packets_received', index=0,
      number=50, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bytes_received', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.bytes_received', index=1,
      number=51, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='packets_sent', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.packets_sent', index=2,
      number=52, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bytes_sent', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.bytes_sent', index=3,
      number=53, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='multicast_packets_received', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.multicast_packets_received', index=4,
      number=54, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='broadcast_packets_received', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.broadcast_packets_received', index=5,
      number=55, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='multicast_packets_sent', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.multicast_packets_sent', index=6,
      number=56, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='broadcast_packets_sent', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.broadcast_packets_sent', index=7,
      number=57, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_drops', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.output_drops', index=8,
      number=58, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_queue_drops', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.output_queue_drops', index=9,
      number=59, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_drops', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.input_drops', index=10,
      number=60, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_queue_drops', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.input_queue_drops', index=11,
      number=61, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='runt_packets_received', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.runt_packets_received', index=12,
      number=62, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='giant_packets_received', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.giant_packets_received', index=13,
      number=63, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='throttled_packets_received', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.throttled_packets_received', index=14,
      number=64, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parity_packets_received', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.parity_packets_received', index=15,
      number=65, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown_protocol_packets_received', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.unknown_protocol_packets_received', index=16,
      number=66, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_errors', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.input_errors', index=17,
      number=67, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='crc_errors', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.crc_errors', index=18,
      number=68, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_overruns', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.input_overruns', index=19,
      number=69, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='framing_errors_received', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.framing_errors_received', index=20,
      number=70, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_ignored_packets', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.input_ignored_packets', index=21,
      number=71, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_aborts', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.input_aborts', index=22,
      number=72, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_errors', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.output_errors', index=23,
      number=73, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_underruns', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.output_underruns', index=24,
      number=74, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_buffer_failures', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.output_buffer_failures', index=25,
      number=75, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_buffers_swapped_out', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.output_buffers_swapped_out', index=26,
      number=76, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='applique', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.applique', index=27,
      number=77, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resets', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.resets', index=28,
      number=78, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='carrier_transitions', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.carrier_transitions', index=29,
      number=79, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='availability_flag', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.availability_flag', index=30,
      number=80, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_data_time', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.last_data_time', index=31,
      number=81, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seconds_since_last_clear_counters', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.seconds_since_last_clear_counters', index=32,
      number=82, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_discontinuity_time', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.last_discontinuity_time', index=33,
      number=83, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seconds_since_packet_received', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.seconds_since_packet_received', index=34,
      number=84, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seconds_since_packet_sent', full_name='cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic.seconds_since_packet_sent', index=35,
      number=85, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=1228,
)

DESCRIPTOR.message_types_by_name['ifstatsbag_generic_KEYS'] = _IFSTATSBAG_GENERIC_KEYS
DESCRIPTOR.message_types_by_name['ifstatsbag_generic'] = _IFSTATSBAG_GENERIC

ifstatsbag_generic_KEYS = _reflection.GeneratedProtocolMessageType('ifstatsbag_generic_KEYS', (_message.Message,), dict(
  DESCRIPTOR = _IFSTATSBAG_GENERIC_KEYS,
  __module__ = 'ifstatsbag_generic_pb2'
  # @@protoc_insertion_point(class_scope:cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic_KEYS)
  ))
_sym_db.RegisterMessage(ifstatsbag_generic_KEYS)

ifstatsbag_generic = _reflection.GeneratedProtocolMessageType('ifstatsbag_generic', (_message.Message,), dict(
  DESCRIPTOR = _IFSTATSBAG_GENERIC,
  __module__ = 'ifstatsbag_generic_pb2'
  # @@protoc_insertion_point(class_scope:cisco_ios_xr_infra_statsd_oper.infra_statistics.interfaces.interface.latest.generic_counters.ifstatsbag_generic)
  ))
_sym_db.RegisterMessage(ifstatsbag_generic)


# @@protoc_insertion_point(module_scope)
