# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logical_port.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import telemetry_top_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='logical_port.proto',
  package='',
  serialized_pb=_b('\n\x12logical_port.proto\x1a\x13telemetry_top.proto\"<\n\x0bLogicalPort\x12-\n\x0einterface_info\x18\x01 \x03(\x0b\x32\x15.LogicalInterfaceInfo\"\x86\x02\n\x14LogicalInterfaceInfo\x12\x16\n\x07if_name\x18\x01 \x02(\tB\x05\x82@\x02\x08\x01\x12\x18\n\tinit_time\x18\x02 \x02(\x04\x42\x05\x82@\x02\x10\x01\x12\x1c\n\rsnmp_if_index\x18\x03 \x01(\rB\x05\x82@\x02\x08\x01\x12\x1d\n\x0eparent_ae_name\x18\x04 \x01(\tB\x05\x82@\x02\x08\x01\x12-\n\ringress_stats\x18\x05 \x01(\x0b\x32\x16.IngressInterfaceStats\x12+\n\x0c\x65gress_stats\x18\x06 \x01(\x0b\x32\x15.EgressInterfaceStats\x12#\n\x08op_state\x18\x07 \x01(\x0b\x32\x11.OperationalState\"\xbf\x01\n\x15IngressInterfaceStats\x12\x19\n\nif_packets\x18\x01 \x02(\x04\x42\x05\x82@\x02\x18\x01\x12\x18\n\tif_octets\x18\x02 \x02(\x04\x42\x05\x82@\x02\x18\x01\x12\x1f\n\x10if_ucast_packets\x18\x03 \x01(\x04\x42\x05\x82@\x02\x18\x01\x12\x1f\n\x10if_mcast_packets\x18\x04 \x02(\x04\x42\x05\x82@\x02\x18\x01\x12/\n\x0bif_fc_stats\x18\x05 \x03(\x0b\x32\x1a.ForwardingClassAccounting\"K\n\x14\x45gressInterfaceStats\x12\x19\n\nif_packets\x18\x01 \x02(\x04\x42\x05\x82@\x02\x18\x01\x12\x18\n\tif_octets\x18\x02 \x02(\x04\x42\x05\x82@\x02\x18\x01\".\n\x10OperationalState\x12\x1a\n\x12operational_status\x18\x01 \x01(\t\"\x84\x01\n\x19\x46orwardingClassAccounting\x12\x18\n\tif_family\x18\x01 \x01(\tB\x05\x82@\x02\x08\x01\x12\x18\n\tfc_number\x18\x02 \x01(\rB\x05\x82@\x02\x08\x01\x12\x19\n\nif_packets\x18\x03 \x01(\x04\x42\x05\x82@\x02\x18\x01\x12\x18\n\tif_octets\x18\x04 \x01(\x04\x42\x05\x82@\x02\x18\x01:F\n\x17jnprLogicalInterfaceExt\x12\x17.JuniperNetworksSensors\x18\x07 \x01(\x0b\x32\x0c.LogicalPort')
  ,
  dependencies=[telemetry_top_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


JNPRLOGICALINTERFACEEXT_FIELD_NUMBER = 7
jnprLogicalInterfaceExt = _descriptor.FieldDescriptor(
  name='jnprLogicalInterfaceExt', full_name='jnprLogicalInterfaceExt', index=0,
  number=7, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_LOGICALPORT = _descriptor.Descriptor(
  name='LogicalPort',
  full_name='LogicalPort',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='interface_info', full_name='LogicalPort.interface_info', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=103,
)


_LOGICALINTERFACEINFO = _descriptor.Descriptor(
  name='LogicalInterfaceInfo',
  full_name='LogicalInterfaceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='if_name', full_name='LogicalInterfaceInfo.if_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))),
    _descriptor.FieldDescriptor(
      name='init_time', full_name='LogicalInterfaceInfo.init_time', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\020\001'))),
    _descriptor.FieldDescriptor(
      name='snmp_if_index', full_name='LogicalInterfaceInfo.snmp_if_index', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))),
    _descriptor.FieldDescriptor(
      name='parent_ae_name', full_name='LogicalInterfaceInfo.parent_ae_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))),
    _descriptor.FieldDescriptor(
      name='ingress_stats', full_name='LogicalInterfaceInfo.ingress_stats', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='egress_stats', full_name='LogicalInterfaceInfo.egress_stats', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='op_state', full_name='LogicalInterfaceInfo.op_state', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=368,
)


_INGRESSINTERFACESTATS = _descriptor.Descriptor(
  name='IngressInterfaceStats',
  full_name='IngressInterfaceStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='if_packets', full_name='IngressInterfaceStats.if_packets', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))),
    _descriptor.FieldDescriptor(
      name='if_octets', full_name='IngressInterfaceStats.if_octets', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))),
    _descriptor.FieldDescriptor(
      name='if_ucast_packets', full_name='IngressInterfaceStats.if_ucast_packets', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))),
    _descriptor.FieldDescriptor(
      name='if_mcast_packets', full_name='IngressInterfaceStats.if_mcast_packets', index=3,
      number=4, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))),
    _descriptor.FieldDescriptor(
      name='if_fc_stats', full_name='IngressInterfaceStats.if_fc_stats', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=371,
  serialized_end=562,
)


_EGRESSINTERFACESTATS = _descriptor.Descriptor(
  name='EgressInterfaceStats',
  full_name='EgressInterfaceStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='if_packets', full_name='EgressInterfaceStats.if_packets', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))),
    _descriptor.FieldDescriptor(
      name='if_octets', full_name='EgressInterfaceStats.if_octets', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=564,
  serialized_end=639,
)


_OPERATIONALSTATE = _descriptor.Descriptor(
  name='OperationalState',
  full_name='OperationalState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operational_status', full_name='OperationalState.operational_status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=641,
  serialized_end=687,
)


_FORWARDINGCLASSACCOUNTING = _descriptor.Descriptor(
  name='ForwardingClassAccounting',
  full_name='ForwardingClassAccounting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='if_family', full_name='ForwardingClassAccounting.if_family', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))),
    _descriptor.FieldDescriptor(
      name='fc_number', full_name='ForwardingClassAccounting.fc_number', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))),
    _descriptor.FieldDescriptor(
      name='if_packets', full_name='ForwardingClassAccounting.if_packets', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))),
    _descriptor.FieldDescriptor(
      name='if_octets', full_name='ForwardingClassAccounting.if_octets', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=690,
  serialized_end=822,
)

_LOGICALPORT.fields_by_name['interface_info'].message_type = _LOGICALINTERFACEINFO
_LOGICALINTERFACEINFO.fields_by_name['ingress_stats'].message_type = _INGRESSINTERFACESTATS
_LOGICALINTERFACEINFO.fields_by_name['egress_stats'].message_type = _EGRESSINTERFACESTATS
_LOGICALINTERFACEINFO.fields_by_name['op_state'].message_type = _OPERATIONALSTATE
_INGRESSINTERFACESTATS.fields_by_name['if_fc_stats'].message_type = _FORWARDINGCLASSACCOUNTING
DESCRIPTOR.message_types_by_name['LogicalPort'] = _LOGICALPORT
DESCRIPTOR.message_types_by_name['LogicalInterfaceInfo'] = _LOGICALINTERFACEINFO
DESCRIPTOR.message_types_by_name['IngressInterfaceStats'] = _INGRESSINTERFACESTATS
DESCRIPTOR.message_types_by_name['EgressInterfaceStats'] = _EGRESSINTERFACESTATS
DESCRIPTOR.message_types_by_name['OperationalState'] = _OPERATIONALSTATE
DESCRIPTOR.message_types_by_name['ForwardingClassAccounting'] = _FORWARDINGCLASSACCOUNTING
DESCRIPTOR.extensions_by_name['jnprLogicalInterfaceExt'] = jnprLogicalInterfaceExt

LogicalPort = _reflection.GeneratedProtocolMessageType('LogicalPort', (_message.Message,), dict(
  DESCRIPTOR = _LOGICALPORT,
  __module__ = 'logical_port_pb2'
  # @@protoc_insertion_point(class_scope:LogicalPort)
  ))
_sym_db.RegisterMessage(LogicalPort)

LogicalInterfaceInfo = _reflection.GeneratedProtocolMessageType('LogicalInterfaceInfo', (_message.Message,), dict(
  DESCRIPTOR = _LOGICALINTERFACEINFO,
  __module__ = 'logical_port_pb2'
  # @@protoc_insertion_point(class_scope:LogicalInterfaceInfo)
  ))
_sym_db.RegisterMessage(LogicalInterfaceInfo)

IngressInterfaceStats = _reflection.GeneratedProtocolMessageType('IngressInterfaceStats', (_message.Message,), dict(
  DESCRIPTOR = _INGRESSINTERFACESTATS,
  __module__ = 'logical_port_pb2'
  # @@protoc_insertion_point(class_scope:IngressInterfaceStats)
  ))
_sym_db.RegisterMessage(IngressInterfaceStats)

EgressInterfaceStats = _reflection.GeneratedProtocolMessageType('EgressInterfaceStats', (_message.Message,), dict(
  DESCRIPTOR = _EGRESSINTERFACESTATS,
  __module__ = 'logical_port_pb2'
  # @@protoc_insertion_point(class_scope:EgressInterfaceStats)
  ))
_sym_db.RegisterMessage(EgressInterfaceStats)

OperationalState = _reflection.GeneratedProtocolMessageType('OperationalState', (_message.Message,), dict(
  DESCRIPTOR = _OPERATIONALSTATE,
  __module__ = 'logical_port_pb2'
  # @@protoc_insertion_point(class_scope:OperationalState)
  ))
_sym_db.RegisterMessage(OperationalState)

ForwardingClassAccounting = _reflection.GeneratedProtocolMessageType('ForwardingClassAccounting', (_message.Message,), dict(
  DESCRIPTOR = _FORWARDINGCLASSACCOUNTING,
  __module__ = 'logical_port_pb2'
  # @@protoc_insertion_point(class_scope:ForwardingClassAccounting)
  ))
_sym_db.RegisterMessage(ForwardingClassAccounting)

jnprLogicalInterfaceExt.message_type = _LOGICALPORT
telemetry_top_pb2.JuniperNetworksSensors.RegisterExtension(jnprLogicalInterfaceExt)

_LOGICALINTERFACEINFO.fields_by_name['if_name'].has_options = True
_LOGICALINTERFACEINFO.fields_by_name['if_name']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))
_LOGICALINTERFACEINFO.fields_by_name['init_time'].has_options = True
_LOGICALINTERFACEINFO.fields_by_name['init_time']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\020\001'))
_LOGICALINTERFACEINFO.fields_by_name['snmp_if_index'].has_options = True
_LOGICALINTERFACEINFO.fields_by_name['snmp_if_index']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))
_LOGICALINTERFACEINFO.fields_by_name['parent_ae_name'].has_options = True
_LOGICALINTERFACEINFO.fields_by_name['parent_ae_name']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))
_INGRESSINTERFACESTATS.fields_by_name['if_packets'].has_options = True
_INGRESSINTERFACESTATS.fields_by_name['if_packets']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))
_INGRESSINTERFACESTATS.fields_by_name['if_octets'].has_options = True
_INGRESSINTERFACESTATS.fields_by_name['if_octets']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))
_INGRESSINTERFACESTATS.fields_by_name['if_ucast_packets'].has_options = True
_INGRESSINTERFACESTATS.fields_by_name['if_ucast_packets']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))
_INGRESSINTERFACESTATS.fields_by_name['if_mcast_packets'].has_options = True
_INGRESSINTERFACESTATS.fields_by_name['if_mcast_packets']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))
_EGRESSINTERFACESTATS.fields_by_name['if_packets'].has_options = True
_EGRESSINTERFACESTATS.fields_by_name['if_packets']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))
_EGRESSINTERFACESTATS.fields_by_name['if_octets'].has_options = True
_EGRESSINTERFACESTATS.fields_by_name['if_octets']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))
_FORWARDINGCLASSACCOUNTING.fields_by_name['if_family'].has_options = True
_FORWARDINGCLASSACCOUNTING.fields_by_name['if_family']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))
_FORWARDINGCLASSACCOUNTING.fields_by_name['fc_number'].has_options = True
_FORWARDINGCLASSACCOUNTING.fields_by_name['fc_number']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))
_FORWARDINGCLASSACCOUNTING.fields_by_name['if_packets'].has_options = True
_FORWARDINGCLASSACCOUNTING.fields_by_name['if_packets']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))
_FORWARDINGCLASSACCOUNTING.fields_by_name['if_octets'].has_options = True
_FORWARDINGCLASSACCOUNTING.fields_by_name['if_octets']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\030\001'))
# @@protoc_insertion_point(module_scope)
