# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telemetry_top.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import google.protobuf.descriptor_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='telemetry_top.proto',
  package='',
  serialized_pb=_b('\n\x13telemetry_top.proto\x1a google/protobuf/descriptor.proto\"c\n\x15TelemetryFieldOptions\x12\x0e\n\x06is_key\x18\x01 \x01(\x08\x12\x14\n\x0cis_timestamp\x18\x02 \x01(\x08\x12\x12\n\nis_counter\x18\x03 \x01(\x08\x12\x10\n\x08is_gauge\x18\x04 \x01(\x08\"\xaa\x02\n\x0fTelemetryStream\x12\x18\n\tsystem_id\x18\x01 \x02(\tB\x05\x82@\x02\x08\x01\x12\x1b\n\x0c\x63omponent_id\x18\x02 \x01(\rB\x05\x82@\x02\x08\x01\x12\x1f\n\x10sub_component_id\x18\x03 \x01(\rB\x05\x82@\x02\x08\x01\x12\x1a\n\x0bsensor_name\x18\x04 \x01(\tB\x05\x82@\x02\x08\x01\x12\x17\n\x0fsequence_number\x18\x05 \x01(\r\x12\x18\n\ttimestamp\x18\x06 \x01(\x04\x42\x05\x82@\x02\x10\x01\x12\x15\n\rversion_major\x18\x07 \x01(\r\x12\x15\n\rversion_minor\x18\x08 \x01(\r\x12\x1a\n\x04ietf\x18\x64 \x01(\x0b\x32\x0c.IETFSensors\x12&\n\nenterprise\x18\x65 \x01(\x0b\x32\x12.EnterpriseSensors\"\x17\n\x0bIETFSensors*\x08\x08\x01\x10\x80\x80\x80\x80\x02\"\x1d\n\x11\x45nterpriseSensors*\x08\x08\x01\x10\x80\x80\x80\x80\x02\"\"\n\x16JuniperNetworksSensors*\x08\x08\x01\x10\x80\x80\x80\x80\x02:Q\n\x11telemetry_options\x12\x1d.google.protobuf.FieldOptions\x18\x80\x08 \x01(\x0b\x32\x16.TelemetryFieldOptions:E\n\x0fjuniperNetworks\x12\x12.EnterpriseSensors\x18\xcc\x14 \x01(\x0b\x32\x17.JuniperNetworksSensors')
  ,
  dependencies=[google.protobuf.descriptor_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


TELEMETRY_OPTIONS_FIELD_NUMBER = 1024
telemetry_options = _descriptor.FieldDescriptor(
  name='telemetry_options', full_name='telemetry_options', index=0,
  number=1024, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
JUNIPERNETWORKS_FIELD_NUMBER = 2636
juniperNetworks = _descriptor.FieldDescriptor(
  name='juniperNetworks', full_name='juniperNetworks', index=1,
  number=2636, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_TELEMETRYFIELDOPTIONS = _descriptor.Descriptor(
  name='TelemetryFieldOptions',
  full_name='TelemetryFieldOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_key', full_name='TelemetryFieldOptions.is_key', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_timestamp', full_name='TelemetryFieldOptions.is_timestamp', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_counter', full_name='TelemetryFieldOptions.is_counter', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_gauge', full_name='TelemetryFieldOptions.is_gauge', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=156,
)


_TELEMETRYSTREAM = _descriptor.Descriptor(
  name='TelemetryStream',
  full_name='TelemetryStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='system_id', full_name='TelemetryStream.system_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))),
    _descriptor.FieldDescriptor(
      name='component_id', full_name='TelemetryStream.component_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))),
    _descriptor.FieldDescriptor(
      name='sub_component_id', full_name='TelemetryStream.sub_component_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))),
    _descriptor.FieldDescriptor(
      name='sensor_name', full_name='TelemetryStream.sensor_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))),
    _descriptor.FieldDescriptor(
      name='sequence_number', full_name='TelemetryStream.sequence_number', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='TelemetryStream.timestamp', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\020\001'))),
    _descriptor.FieldDescriptor(
      name='version_major', full_name='TelemetryStream.version_major', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version_minor', full_name='TelemetryStream.version_minor', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ietf', full_name='TelemetryStream.ietf', index=8,
      number=100, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enterprise', full_name='TelemetryStream.enterprise', index=9,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=457,
)


_IETFSENSORS = _descriptor.Descriptor(
  name='IETFSensors',
  full_name='IETFSensors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(1, 536870912), ],
  oneofs=[
  ],
  serialized_start=459,
  serialized_end=482,
)


_ENTERPRISESENSORS = _descriptor.Descriptor(
  name='EnterpriseSensors',
  full_name='EnterpriseSensors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(1, 536870912), ],
  oneofs=[
  ],
  serialized_start=484,
  serialized_end=513,
)


_JUNIPERNETWORKSSENSORS = _descriptor.Descriptor(
  name='JuniperNetworksSensors',
  full_name='JuniperNetworksSensors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(1, 536870912), ],
  oneofs=[
  ],
  serialized_start=515,
  serialized_end=549,
)

_TELEMETRYSTREAM.fields_by_name['ietf'].message_type = _IETFSENSORS
_TELEMETRYSTREAM.fields_by_name['enterprise'].message_type = _ENTERPRISESENSORS
DESCRIPTOR.message_types_by_name['TelemetryFieldOptions'] = _TELEMETRYFIELDOPTIONS
DESCRIPTOR.message_types_by_name['TelemetryStream'] = _TELEMETRYSTREAM
DESCRIPTOR.message_types_by_name['IETFSensors'] = _IETFSENSORS
DESCRIPTOR.message_types_by_name['EnterpriseSensors'] = _ENTERPRISESENSORS
DESCRIPTOR.message_types_by_name['JuniperNetworksSensors'] = _JUNIPERNETWORKSSENSORS
DESCRIPTOR.extensions_by_name['telemetry_options'] = telemetry_options
DESCRIPTOR.extensions_by_name['juniperNetworks'] = juniperNetworks

TelemetryFieldOptions = _reflection.GeneratedProtocolMessageType('TelemetryFieldOptions', (_message.Message,), dict(
  DESCRIPTOR = _TELEMETRYFIELDOPTIONS,
  __module__ = 'telemetry_top_pb2'
  # @@protoc_insertion_point(class_scope:TelemetryFieldOptions)
  ))
_sym_db.RegisterMessage(TelemetryFieldOptions)

TelemetryStream = _reflection.GeneratedProtocolMessageType('TelemetryStream', (_message.Message,), dict(
  DESCRIPTOR = _TELEMETRYSTREAM,
  __module__ = 'telemetry_top_pb2'
  # @@protoc_insertion_point(class_scope:TelemetryStream)
  ))
_sym_db.RegisterMessage(TelemetryStream)

IETFSensors = _reflection.GeneratedProtocolMessageType('IETFSensors', (_message.Message,), dict(
  DESCRIPTOR = _IETFSENSORS,
  __module__ = 'telemetry_top_pb2'
  # @@protoc_insertion_point(class_scope:IETFSensors)
  ))
_sym_db.RegisterMessage(IETFSensors)

EnterpriseSensors = _reflection.GeneratedProtocolMessageType('EnterpriseSensors', (_message.Message,), dict(
  DESCRIPTOR = _ENTERPRISESENSORS,
  __module__ = 'telemetry_top_pb2'
  # @@protoc_insertion_point(class_scope:EnterpriseSensors)
  ))
_sym_db.RegisterMessage(EnterpriseSensors)

JuniperNetworksSensors = _reflection.GeneratedProtocolMessageType('JuniperNetworksSensors', (_message.Message,), dict(
  DESCRIPTOR = _JUNIPERNETWORKSSENSORS,
  __module__ = 'telemetry_top_pb2'
  # @@protoc_insertion_point(class_scope:JuniperNetworksSensors)
  ))
_sym_db.RegisterMessage(JuniperNetworksSensors)

telemetry_options.message_type = _TELEMETRYFIELDOPTIONS
google.protobuf.descriptor_pb2.FieldOptions.RegisterExtension(telemetry_options)
juniperNetworks.message_type = _JUNIPERNETWORKSSENSORS
EnterpriseSensors.RegisterExtension(juniperNetworks)

_TELEMETRYSTREAM.fields_by_name['system_id'].has_options = True
_TELEMETRYSTREAM.fields_by_name['system_id']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))
_TELEMETRYSTREAM.fields_by_name['component_id'].has_options = True
_TELEMETRYSTREAM.fields_by_name['component_id']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))
_TELEMETRYSTREAM.fields_by_name['sub_component_id'].has_options = True
_TELEMETRYSTREAM.fields_by_name['sub_component_id']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))
_TELEMETRYSTREAM.fields_by_name['sensor_name'].has_options = True
_TELEMETRYSTREAM.fields_by_name['sensor_name']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\010\001'))
_TELEMETRYSTREAM.fields_by_name['timestamp'].has_options = True
_TELEMETRYSTREAM.fields_by_name['timestamp']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202@\002\020\001'))
# @@protoc_insertion_point(module_scope)
